### ISSUE TITLE
clarification on cache package

### ISSUE THREAD

**Issue by davidbirdsong** [syndtr/goleveldb#119]
I've noticed that holding open a `Handle` reference is required for a `Node` object to not be cleaned up. 
Is this correct? When doing so, any attempts at Deleting or Evicting a namespace-key combination return true, but the object lives on and returns to other callers calling `Get`.

If I've understood this correctly, I don't understand the usefulness of `*Cache.Delete` or `*Cache.Evict`, it seems a caller that need to either clear the Node out or at the very least block other callers from finding the `Node` object need to find the holder of the `Handle` and call `*Handle.Release()`

Let me know if you need me to clarify. I appreciate this library, it's been very useful to me.

**Comment by syndtr** [comment]
First, there are two conditions that must be met before a cached object can be released:
1. Not in "cache tree"
2. No one holds reference to the object, i.e `Node`

What `Cache.Evict()` do is to override caching algorithm and remove the object from the "cache tree" so that the object will be released as soon as no one holds reference to it (or immediately if no one use this cached object). But the object will be "promoted" (inserted back) into the "cache tree" when someone call `Cache.Get()` on this object (a cache hit), this is where `Cache.Delete()` step in, not only it evict the cache object from the cache tree, but it also "ban" the object from getting "promoted", this guarantee that the object will not get cached.

Please note that `Cache` also act as concurrency control.

Hope that help. Sorry if confusing, I'm not very good with explaining things :)

**Comment by davidbirdsong** [comment]
I hope it's ok to ask a follow-up question on `Cache`.

In a `Cache.Get()`, the user supplies a function which allows population to be user-driven--this is very useful. What contention occurs during the `Cache.Get`? If a user's function takes 10 seconds to complete and return, which callers are blocked, only calls to the same namespace and key or is there a shard space or some other partitioning internally that will be blocked?

I read the code, but I'll admit I don't quite follow the lock-free structures internally well enough to reason about it myself.

**Comment by syndtr** [comment]
> I hope it's ok to ask a follow-up question on `Cache`.

No problem at all.

> In a `Cache.Get()`, the user supplies a function which allows population to be user-driven--this is very useful. What contention occurs during the `Cache.Get`? If a user's function takes 10 seconds to complete and return, which callers are blocked, only calls to the same namespace and key or is there a shard space or some other partitioning internally that will be blocked?

Only calls to the same key within same namespace is blocked.

> I read the code, but I'll admit I don't quite follow the lock-free structures internally well enough to reason about it myself.

The lock-free bits is just for the hash table.
