### ISSUE TITLE
Iterator that only returns keys

### ISSUE THREAD

**Issue by whyrusleeping** [syndtr/goleveldb#159]
Is there any way i can iterate over *just* the keys in a given database? Pulling up the values at the same time might be causing perf issues in some of my applications.

**Comment by syndtr** [comment]
This can't be done in leveldb, due to the nature of how key and value arranged in leveldb, pulling key-only is impossible.

Easy fix is to create two key-range, one is key-only (some sort of index) and the other contains data. You can iterate over this key-only key-range, when you need the data you can just Get on data key-range.
