### ISSUE TITLE
How to have a wrapper where it's easy to use leveldb or memdb as backend

### ISSUE THREAD

**Issue by ThibaultRiviere** [syndtr/goleveldb#160]
I'm new in go and i didn't see how to do it

**Comment by syndtr** [comment]
Currently memdb isn't ready for general use, it can't even shrink or reclaim its KV buffer yet, so when you deleting an entry it would only remove the entry node but the KV buffer itself will keep growing. This is not an issue in leveldb, since leveldb use memdb in strictly append-only, but depending on your use-case this may not what you want.
