### ISSUE TITLE
All level files are 2MB

### ISSUE THREAD

**Issue by bradfitz** [syndtr/goleveldb#212]
We're trying to use goleveldb for @perkeep but @mpl and I have noticed performance problems over time.

My index in goleveldb is 1.3GB, but every level has files that are about 2MB:

```
bard:leveldb-weird $ du -h .
1.3G    .

bard:leveldb-weird $ ls -l *.ldb | wc -l
767

bard:leveldb-weird $ ls -l | sort -k5 -n | tail -10
-rw-r--r-- 1 bradfitz bradfitz 2322555 Apr 21 20:58 069086.ldb
-rw-r--r-- 1 bradfitz bradfitz 2323338 Apr 21 20:58 069090.ldb
-rw-r--r-- 1 bradfitz bradfitz 2324125 Apr 21 20:58 069089.ldb
-rw-r--r-- 1 bradfitz bradfitz 2324145 Apr 21 20:58 069095.ldb
-rw-r--r-- 1 bradfitz bradfitz 2324431 Apr 21 20:58 069093.ldb
-rw-r--r-- 1 bradfitz bradfitz 2324465 Apr 21 20:58 069094.ldb
-rw-r--r-- 1 bradfitz bradfitz 2324656 Apr 21 20:58 069088.ldb
-rw-r--r-- 1 bradfitz bradfitz 2324715 Apr 21 20:58 069091.ldb
-rw-r--r-- 1 bradfitz bradfitz 2325053 Apr 21 20:58 069092.ldb
-rw-r--r-- 1 bradfitz bradfitz 4619241 Apr 20 10:44 LOG.old

bard:leveldb-weird $ go run ~/leveldb.go .
2018/04/22 11:44:16.588499 start
2018/04/22 11:44:16.709327 opened = *leveldb.DB
2018/04/22 11:44:16.709348 files at level0 = 0
2018/04/22 11:44:16.709353 files at level1 = 70
2018/04/22 11:44:16.709358 files at level2 = 593
2018/04/22 11:44:16.709374 files at level3 = 104
2018/04/22 11:44:16.709378 files at level4 = 0
2018/04/22 11:44:16.709749 closed
```

If I compact it all, I get 617 2MB files at level3:

```
2018/04/22 11:43:12.808138 start
2018/04/22 11:43:12.820236 opened = *leveldb.DB
2018/04/22 11:43:12.820258 files at level0 = 0
2018/04/22 11:43:12.820266 files at level1 = 0
2018/04/22 11:43:12.820276 files at level2 = 0
2018/04/22 11:43:12.820288 files at level3 = 617
2018/04/22 11:43:12.820300 files at level4 = 0
2018/04/22 11:43:12.820592 closed
```

We are opening it with all the default Options. We specify no options values.

The docs at https://godoc.org/github.com/syndtr/goleveldb/leveldb/opt#Options.CompactionTableSize say:

```
    // CompactionTableSize limits size of 'sorted table' that compaction generates.
    // The limits for each level will be calculated as:
    //   CompactionTableSize * (CompactionTableSizeMultiplier ^ Level)
    // The multiplier for each level can also fine-tuned using CompactionTableSizeMultiplierPerLevel.
    //
    // The default value is 2MiB.
    CompactionTableSize int
```

That suggests that level0 should be 2MB, and subsequent levels should be bigger.

But we're seeing 2MB for all files, which isn't very performant and wastes a lot of file descriptors.

Are we using it wrong, or is this a bug?

Thanks!

/cc @rhysh

**Comment by rhysh** [comment]
> subsequent levels should be bigger.

The subsequent levels are bigger, but the files (with default settings) are the same size. Subsequent levels include more files.

`CompactionTableSize * (CompactionTableSizeMultiplier ^ Level)` for your example is 2 MiB * (1 ^ 2), so level2's files are 2 MiB each. The total size of level2 is `CompactionTotalSize * (CompactionTotalSizeMultiplier ^ Level)`, 10 MiB * (10 ^ 2) = 1000 MiB.

It's been a couple of years since I've tried adjusting those knobs, but I recall it being fruitful. I don't know my way around the settings well, and the variable names (some with `Table`, some with  `Total`) all look similar to me.

To start off: The files are never modified once they're written. Data starts in low-numbered levels, and migrates to higher levels as new data comes in. The mechanism for that is to read one file from level K and to read N files (10, by default) from level K+1, writing out N+1 (11) files in level K+1. The database then deletes the previous files (once they're no longer referenced by iterators). When the files are 2 MB, that process involves reading 22 MB and writing 22 MB.

Because the compaction process discards the affected files, there's a benefit to keeping them somewhat small: Using larger files means the compaction process will require reading and writing more data, which could be disruptive for latency-sensitive applications. I think that's one of the primary tradeoffs you'll get with these settings.

> But we're seeing 2MB for all files, which isn't very performant and wastes a lot of file descriptors.

To trade latency for fewer files, `CompactionTableSizeMultiplier` might help. If you need to conserve file descriptors (rather than inodes), `OpenFilesCacheCapacity` should limit the number of cached FDs.

**Comment by syndtr** [comment]
What @rhysh said is spot on. @bradfitz Basically you need to set `CompactionTableSizeMultiplier > 1` if you want subsequent table size to be bigger. The default value is `1` which means all level will have same size.
