### ISSUE TITLE
Difference between github.com/golang/leveldb and syndtr/goleveldb

### ISSUE THREAD

**Issue by linrl3** [syndtr/goleveldb#386]
May I ask what is the difference between github.com/golang/leveldb and syndtr/goleveldb?

**Comment by Alex-duzhichao** [comment]
> May I ask what is the difference between github.com/golang/leveldb and syndtr/goleveldb?

@linrl3  As I know, `github.com/golang/leveldb` and `syndtr/goleveldb` are both inspired by google's C++ leveldb and try to implement leveldb using golang. But they do it in different ways.
`github.com/golang/leveldb`  is incomplete and not ready for production use, while `syndtr/goleveldb` can be used in production environment.
There is another project [cockroachdb/pebble](https://github.com/cockroachdb/pebble) which is forked from `github.com/golang/leveldb` and completely rewritten so that can be used in production environment.

**Comment by linrl3** [comment]
@Alex-duzhichao Thank you for the answer.
